# This file was generated by GoReleaser. DO NOT EDIT.
cask "iicu" do
  version "0.1.1"

  on_macos do
    on_intel do
      sha256 "f5387c9af0052bc51b8f679b1db1b018016e9bbcb92e80f75b68c6d8240b6d44"
      url "https://github.com/elricho/iicu/releases/download/v#{version}/iicu_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "04be92c34f0d02f515fafae438714fb08b73294ff18b3e6ec9136385b4f3c579"
      url "https://github.com/elricho/iicu/releases/download/v#{version}/iicu_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "67e90daf53ae5d94015260e74cca0137e29ccbaf2313cc9df3bf6192cf3e2611"
      url "https://github.com/elricho/iicu/releases/download/v#{version}/iicu_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "2b1a315465dcf5387d649b1db05c7973be942d86b3519a55222daa4ae2aaa304"
      url "https://github.com/elricho/iicu/releases/download/v#{version}/iicu_#{version}_linux_arm64.tar.gz"
    end
  end

  name "iicu"
  desc "CLI for the intervals.icu training platform"
  homepage "https://github.com/elricho/iicu"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "iicu"

  postflight do
    if system_command("/usr/bin/xattr", args: ["-h"]).exit_status == 0
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/iicu"]
    end
  end

  # No zap stanza required

end
