# This file was generated by GoReleaser. DO NOT EDIT.
cask "iicu" do
  version "0.1.2"

  on_macos do
    on_intel do
      sha256 "ca1d83624337ad5442bc16860103cc10518d2eab7b6dafd2c3dceadd0b732f25"
      url "https://github.com/elricho/iicu/releases/download/v#{version}/iicu_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "a21af9ba2e0a2b1f122d86630b8ed0be38678c2888894624d6765b197f6954a7"
      url "https://github.com/elricho/iicu/releases/download/v#{version}/iicu_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "a2af2d88f65d1b1a9ee312b708820ed777fa14cadff91b453c87e279fc04e2f5"
      url "https://github.com/elricho/iicu/releases/download/v#{version}/iicu_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "a069d9d9718f316cdbb91a7f610f31216454081f6123e1e8da27b006f5fd5dcd"
      url "https://github.com/elricho/iicu/releases/download/v#{version}/iicu_#{version}_linux_arm64.tar.gz"
    end
  end

  name "iicu"
  desc "CLI for the intervals.icu training platform"
  homepage "https://github.com/elricho/iicu"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "iicu"

  postflight do
    if system_command("/usr/bin/xattr", args: ["-h"]).exit_status == 0
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/iicu"]
    end
  end

  # No zap stanza required

end
