# This file was generated by GoReleaser. DO NOT EDIT.
cask "iicu" do
  version "0.1.0"

  on_macos do
    on_intel do
      sha256 "24c5596d081ed7295346447d6a934dc8d013bc9ed9c6b27d8ddc3f87ac062e2d"
      url "https://github.com/elricho/intervals-cli/releases/download/v#{version}/iicu_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "8d6f42a9fee63c530a8429816f4d044b2f5e37e02abeed23ea6bf87024de0127"
      url "https://github.com/elricho/intervals-cli/releases/download/v#{version}/iicu_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "da2a9e5bf2cb78bc03421cf75e9b19ef30ab6c21f1e61760e22235ff06ca56ab"
      url "https://github.com/elricho/intervals-cli/releases/download/v#{version}/iicu_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "29d9aa261c69b3c44b9a4355bc8e49bc92b49c6e7187c9ca45c5379b34ee1a73"
      url "https://github.com/elricho/intervals-cli/releases/download/v#{version}/iicu_#{version}_linux_arm64.tar.gz"
    end
  end

  name "iicu"
  desc "CLI for the intervals.icu training platform"
  homepage "https://github.com/elricho/intervals-cli"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "iicu"

  postflight do
    if system_command("/usr/bin/xattr", args: ["-h"]).exit_status == 0
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/iicu"]
    end
  end

  # No zap stanza required

end
